version: "3"

services:
  db:
    image: postgres:14-alpine
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
        - db-net

  app:
    container_name: app
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      WAIT_HOSTS: db:5432
    depends_on:
      - db
    ports:
        - "8080:8080"
    networks:
      - db-net

volumes:
    db_data:

networks:
  db-net:
    driver: bridge